import chartedBusImage from "../assets/images/logo.png";
import skyLineBusImage from "../assets/images/logod.png";
import tstcImage from "../assets/images/logon.png";
import heraTakhurImage from "../assets/images/logon.png";
import bhanuPratapImage from "../assets/images/logon.png";
export const busSchedule = {
  bus1: [
    { id: "101", time: "13", cityName: "Hyderabad", distance: 0 },
    { id: "102", time: "14", cityName: "Pune", distance: 200 },
    { id: "103", time: "15", cityName: "Mumbai", distance: 400 },
    { id: "104", time: "16", cityName: "surat", distance: 600 },
    { id: "105", time: "17", cityName: "Indore", distance: 800 },
    { id: "106", time: "18", cityName: "kota", distance: 1000 },
    { id: "107", time: "19", cityName: "Jaipur", distance: 1200 },
    { id: "108", time: "20", cityName: "New Delhi", distance: 1400 },
    { id: "109", time: "21", cityName: "Lakhnow", distance: 1600 },
    { id: "110", time: "22", cityName: "Patna", distance: 1800 },
    { id: "111", time: "23", cityName: "Siliguri", distance: 2000 },
    { id: "112", time: "24", cityName: "Guwahati", distance: 2200 },
  ],

  bus2: [
    { id: "201", time: "03", cityName: "Hyderabad", distance: 0 },
    { id: "202", time: "04", cityName: "Pune", distance: 200 },
    { id: "203", time: "05", cityName: "Mumbai", distance: 400 },
    { id: "204", time: "06", cityName: "surat", distance: 600 },
    { id: "205", time: "07", cityName: "Indore", distance: 800 },
    { id: "206", time: "08", cityName: "kota", distance: 1000 },
    { id: "207", time: "09", cityName: "Jaipur", distance: 1200 },
    { id: "208", time: "10", cityName: "New Delhi", distance: 1400 },
    { id: "209", time: "11", cityName: "Lakhnow", distance: 1600 },
    { id: "210", time: "12", cityName: "Patna", distance: 1800 },
    { id: "211", time: "13", cityName: "Siliguri", distance: 2000 },
    { id: "212", time: "14", cityName: "Guwahati", distance: 2200 },
  ],

  bus3: [
    { id: "301", time: "10", cityName: "Hyderabad", distance: 0 },
    { id: "302", time: "11", cityName: "Pune", distance: 200 },
    { id: "303", time: "12", cityName: "Mumbai", distance: 400 },
    { id: "304", time: "13", cityName: "surat", distance: 600 },
    { id: "305", time: "14", cityName: "Indore", distance: 800 },
    { id: "306", time: "15", cityName: "kota", distance: 1000 },
    { id: "307", time: "16", cityName: "Jaipur", distance: 1200 },
    { id: "308", time: "17", cityName: "New Delhi", distance: 1400 },
    { id: "309", time: "18", cityName: "Lakhnow", distance: 1600 },
    { id: "310", time: "19", cityName: "Patna", distance: 1800 },
    { id: "311", time: "20", cityName: "Siliguri", distance: 2000 },
    { id: "312", time: "21", cityName: "Guwahati", distance: 2200 },
  ],

  bus4: [
    { id: "401", time: "07", cityName: "Hyderabad", distance: 0 },
    { id: "402", time: "08", cityName: "Pune", distance: 200 },
    { id: "403", time: "09", cityName: "Mumbai", distance: 400 },
    { id: "404", time: "10", cityName: "surat", distance: 600 },
    { id: "405", time: "11", cityName: "Indore", distance: 800 },
    { id: "406", time: "12", cityName: "kota", distance: 1000 },
    { id: "407", time: "13", cityName: "Jaipur", distance: 1200 },
    { id: "408", time: "14", cityName: "New Delhi", distance: 1400 },
    { id: "409", time: "15", cityName: "Lakhnow", distance: 1600 },
    { id: "410", time: "16", cityName: "Patna", distance: 1800 },
    { id: "411", time: "17", cityName: "Siliguri", distance: 2000 },
    { id: "412", time: "18", cityName: "Guwahati", distance: 2200 },
  ],
  bus5: [
    { id: "501", time: "05", cityName: "Hyderabad", distance: 0 },
    { id: "502", time: "06", cityName: "Pune", distance: 200 },
    { id: "503", time: "07", cityName: "Mumbai", distance: 400 },
    { id: "504", time: "08", cityName: "surat", distance: 600 },
    { id: "505", time: "09", cityName: "Indore", distance: 800 },
    { id: "506", time: "10", cityName: "kota", distance: 1000 },
    { id: "507", time: "11", cityName: "Jaipur", distance: 1200 },
    { id: "508", time: "12", cityName: "New Delhi", distance: 1400 },
    { id: "509", time: "13", cityName: "Lakhnow", distance: 1600 },
    { id: "510", time: "14", cityName: "Patna", distance: 1800 },
    { id: "511", time: "15", cityName: "Siliguri", distance: 2000 },
    { id: "512", time: "16", cityName: "Guwahati", distance: 2200 },
  ],
};

export const station = [
  { id: "1111", name: "Hyderabad" },
  { id: "1112", name: "Pune" },
  { id: "1113", name: "Mumbai" },
  { id: "1114", name: "surat" },
  { id: "1115", name: "Indore" },
  { id: "1116", name: "kota" },
  { id: "1117", name: "Jaipur" },
  { id: "1118", name: "New Delhi" },
  { id: "1119", name: "Lakhnow" },
  { id: "1120", name: "Patna" },
  { id: "1121", name: "Siliguri" },
  { id: "1122", name: "Guwahati" },
];

export const AvailableBuses = [
  {
    id: "bus1",
    name: "Charted Buses",
    classes: "economy",
    type: ["A/c", "sleeper"],
    image: chartedBusImage,
  },
  {
    id: "bus2",
    name: "Skyline Buses",
    classes: "economy",
    type: ["Non A/c", "seating"],
    image: skyLineBusImage,
  },
  {
    id: "bus3",
    name: "TSRTC",
    classes: "bussiness",
    type: ["A/c", "sleeper"],
    image: tstcImage,
  },
  {
    id: "bus4",
    name: "Heera Takhur Buses",
    classes: "bussiness",
    type: ["A/c", "sleeper"],
    image: heraTakhurImage,
  },
  {
    id: "bus5",
    name: "Bhanu Prataap Buses",
    classes: "economy",
    type: ["Non A/c", "seating"],
    image: bhanuPratapImage,
  },
];

export const sidebarNavItems = [
  {
    display: "Dashboard",
    icon: <ion-icon name="home-outline"></ion-icon>,
    to: "/",
    section: "",
  },
  {
    display: "Profile",
    icon: <ion-icon name="person-outline"></ion-icon>,
    to: "/started",
    section: "started",
  },
  {
    display: "Search Bus",
    icon: <ion-icon name="search-outline"></ion-icon>,
    to: "/search",
    section: "Search",
  },
  {
    display: "Buses",
    icon: <ion-icon name="bus-outline"></ion-icon>,
    to: "/buses",
    section: "Buses",
  },
  {
    display: "Rservation",
    icon: <ion-icon name="ticket-outline"></ion-icon>,
    to: "/reservation",
    section: "Reservation Section",
  },
];

export const busSeats = [
  { id: 1, name: "A1" },
  { id: 2, name: "A2" },
  { id: 3, name: "A3" },
  { id: 99, name: "A4" },
  { id: 4, name: "B1" },
  { id: 5, name: "B2" },
  { id: 6, name: "B3" },
  { id: 7, name: "B4" },
  { id: 8, name: "C1" },
  { id: 9, name: "C2" },
  { id: 10, name: "C3" },
  { id: 11, name: "C4" },
  { id: 12, name: "D1" },
  { id: 13, name: "D2" },
  { id: 14, name: "D3" },
  { id: 15, name: "D4" },
  { id: 16, name: "E1" },
  { id: 17, name: "E2" },
  { id: 18, name: "E3" },
  { id: 19, name: "E4" },
  { id: 20, name: "F1" },
  { id: 21, name: "F2" },
  { id: 22, name: "F3" },
  { id: 23, name: "F4" },
  { id: 24, name: "G1" },
  { id: 25, name: "G2" },
  { id: 26, name: "G3" },
  { id: 27, name: "G4" },
  { id: 28, name: "H1" },
  { id: 29, name: "H2" },
  { id: 30, name: "H3" },
  { id: 31, name: "H4" },
  { id: 32, name: "I1" },
  { id: 33, name: "I2" },
  { id: 34, name: "I3" },
  { id: 35, name: "I4" },
  { id: 36, name: "J1" },
  { id: 37, name: "J2" },
  { id: 38, name: "J3" },
  { id: 39, name: "J4" },
  { id: 40, name: "K1" },
  { id: 41, name: "K2" },
  { id: 42, name: "K3" },
  { id: 43, name: "K4" },
  { id: 44, name: "L1" },
  { id: 45, name: "L2" },
  { id: 46, name: "L3" },
  { id: 47, name: "L4" },
];
